### ISSUE TITLE
Install on SWIFT Poject

### ISSUE THREAD

**Issue by hussan-choudhry** [mogui/MDWamp#31]
Hi,

I am trying to install this via Pods on a swift project and include using a bridging header unfortunately I get the following error:

    GCDAsyncSocket.h file not found

Any ideas about fixing this?

**Comment by Grovespaz** [comment]
I had the same issue, but only because I used the experimental use_frameworks feature of Cocoapods to install another pod. Couldn't undo it either, the project was messed up.

The only way back for me was a clean project, adding just MDWamp to it with Cocoapods fixed the issue. I stopped using the other component (SwiftyJSON), not that is was bad but the combination triggered something.
